---
##################################
# Check requirements before insall
##################################
- name: Set Common Required Package
  set_fact: packages="['bash','curl','ca-certificates']"

- name: Set Ubuntu/Debian Package
  set_fact: apt_packages="['apt-transport-https','ca-certificates']"

- name: Ensure common dependancies presence's
  package:
    name: "{{ packages }}"
    state: present

- name: Ensure specific dependancies presence's (Debian / Ubuntu)
  apt:
    name: "{{ apt_packages }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
