##########################
# Install Docker from repo
##########################
- name: Install Docker
  package:
    name: docker-ce
    state: present
  notify: refresh docker service status

- name: "Set Docker service to state : {{ docker_package_state }} - enabled are restart : {{ docker_service_enabled }}"  
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Notify handlers now to avoid firewall conflicts
  meta: flush_handlers