- name: Get last docker-compose version
  shell: "curl https://api.github.com/repos/docker/compose/releases | grep browser_download_url | head -n 4 | grep Linux | head -n 1 | cut -d '\"' -f 4 | cut -d '/' -f 8"
  failed_when: False
  changed_when: False
  register: last_compose_version
  when: docker_compose_version is not defined

- set_fact:
    docker_compose_version: "{{ last_compose_version }}"
  when: docker_compose_version is not defined

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and last_compose_version.stdout not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: u+x,g+x,o+x
  become: true
  when: docker_compose_version is defined
