---
# tasks file for ansible-role-docker

# Check requirement before installation
- include: check-requirements.yml
# Only Debian/Ubuntu supported for now
- include: setup.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
# Install Docker
- include: install.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Add users to docker group
# Add current user if docker_users is not defined
- set_fact:
    docker_users: [ "{{ ansible_user }}" ]
  when: docker_users is not defined

- include: docker-users.yml

# Install docker compose
- include: install-docker-compose.yml
   when: docker_compose_install is defined and docker_compose_install