######################################
# Setup docker APT repository
######################################
- name: Add Docker apt key
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository_url }}"
    state: present
    update_cache: yes
  become: true
